# Generated by Django 3.2.6 on 2022-07-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_amount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
